### ISSUE TITLE
HNC: Prevent updating labels and annotations with hnc.x-k8s.io suffix on propagated objects

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/hierarchical-namespaces#10]
<a href="https://github.com/yiqigao217"><img src="https://avatars.githubusercontent.com/u/51385444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yiqigao217](https://github.com/yiqigao217)**
_Thursday Apr 29, 2021 at 21:12 GMT_
_Originally opened as https://github.com/kubernetes-sigs/multi-tenancy/issues/1500_

----

The webhook does prevent editing the propagated object itself or labels but doesn't prevent updating annotations:
```
# I'm annotating a propagated object:

$ kubectl annotate role -n b rl propagate.hnc.x-k8s.io/select=abc
role.rbac.authorization.k8s.io/rl annotated

$ kubectl get role -n b -oyaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      propagate.hnc.x-k8s.io/select: abc
    creationTimestamp: "2021-04-29T21:02:29Z"
    labels:
      app.kubernetes.io/managed-by: hnc.x-k8s.io
      hnc.x-k8s.io/inherited-from: a
    name: rl
    namespace: b
    resourceVersion: "5297867"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/b/roles/rl
    uid: 2fc22fd7-7a34-492c-b823-79dd9383b2f8
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - update
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by rahulii** [comment]
@adrianludwin could you give some pointers to get started for this issue? where to look in code for propagated objects?

**Comment by adrianludwin** [comment]
The validator for propagated objects is https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/internal/objects/validator.go.

I just glanced at the code and it looks like we _will_ stop users from modifying any annotation _except_ the annotations that include hnc.x-k8s.io (see [this line](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/bad9db5b05ab1ed6bcc1cdf75b16e7dec5754a6b/internal/objects/validator.go#L279)). The problem is that the `canonical` function returns the object with all HNC labels/annotations stripped out, which probably isn't the right thing to do for this function.

How about this as a solution: [a few lines above](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/bad9db5b05ab1ed6bcc1cdf75b16e7dec5754a6b/internal/objects/validator.go#L269), we check whether the `hnc.x-k8s.io/inherited-from` label has been modified. But really, we don't want _any_ labels or annotations to be modified by users on propagated objects, and this function (`handleInherited`) is _only_ called for propagated objects that are being modified by users. So maybe we should modify this code to check for _all_ HNC labels and annotations (i.e., exactly the ones the `canonical` strips out). Or maybe modify `canonical` so that we can choose whether to strip out the HNC metadata, and only keep it when calling it here.

Whatever you do, can you please add unit tests that fail before you add the fix, and pass afterwards? And note this in the commit comment (e.g. [like this](https://github.com/kubernetes-sigs/hierarchical-namespaces/commit/61e8637b1ed695a919d03c457c795f9d43e9e5e5)). Thanks!

**Comment by adrianludwin** [comment]
I updated the title to reflect what I believe the problem actually is.

**Comment by rahulii** [comment]
@adrianludwin Thanks for the brief explanation .I got the problem.
I will start with writing the unit tests!!
I have one qs though:
why does `canonical()` strips out HNC label?
can't we compare the objects without stripping HNC label?

**Comment by adrianludwin** [comment]
This was fixed correctly

/remove-lifecycle stale
