### ISSUE TITLE
"failed calling webhook" error when creating namespace

### ISSUE THREAD

**Issue by yogeek** [kubernetes-sigs/hierarchical-namespaces#147]
When I create a K8S cluster, some addons are deployed with Jenkins (kubectl, kustomize or helm...) and others with argocd (we are currently migrating our addons deployment to argocd progressively) 

- HNC has been added recently, so it is deployed with ArgoCD
- other legacy addons like external-dns still are deployed with a script in Jenkins

The script installing external-dns is failing at the step of the namespace creation with this error :

```
Error from server (InternalError): Internal error occurred: failed calling webhook "namespaces.hnc.x-k8s.io": Post "[https://hnc-webhook-service.hnc-system.svc:443/validate-v1-namespace?timeout=10s](https://hnc-webhook-service.hnc-system.svc/validate-v1-namespace?timeout=10s)": dial tcp 10.100.115.157:443: connect: connection refused
```

If I launch the pipeline again, all is ok.
I guess this is because the webhook of HNC was not ready yet when the creation of namespace was executed... 

Is it normal that commands like `kubectl create ns external-dns` fail whereas I explicitely added `--excluded-namespace=external-dns` to exclude this namespace from the HNC scope ?

**Comment by erikgb** [comment]
Thanks for registering this issue @yogeek! I am experiencing the same behavior, and it is kinda expected. The excluded/included namespaces in HNC are processed by the webhook server in HNC. The namespace webhook in HNC is configured to fail closed, as it must be, so when the webhook endpoint is not available any namespace API request in the cluster will fail. 😞 

I wonder if https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-825160958 can be used to improve the processing of the included/excluded namespace configuration in HNC? That will allow the API server to be aware of the namespace configuration in HNC. WDYT @adrianludwin? It will only be supported on K8s 1.21+, but should work as now on earlier versions....

Related issue: https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/68

**Comment by adrianludwin** [comment]
Sorry the for delay in responding.

This seems a bit weird to me because starting in HNC v0.9, the webhooks shouldn't touch any namespace that doesn't have the `hnc.x-k8s.io/included-namespace: "true"` label on it, and the HNC controller adds that label itself. So on a new cluster where HNC isn't running yet, nothing should have that label and the webhook should have no effect; by the time HNC has started its controller, it _should_ also have started its webhook service as well.

With that said, if this is happening during an update, that might make a lot more sense since the label will already be present. We're working on making the webhooks highly available which should help here, but we're not there yet. In the meantime, perhaps you could install the HNC webhooks as the last step in the pipeline? Simply take them out of the original manifest, wait for everything else to be installed (which, incidentally, will give HNC some time to start up) and then install the webhooks last?

**Comment by adrianludwin** [comment]
Oh wait, my bad - only the _object_ webhook is restricted to certain namespaces. The _webhook_ namespace operates over all namespaces.

I agree that https://github.com/kubernetes/kubernetes/issues/92157#issuecomment-825160958 could be used to improve this.

**Comment by erikgb** [comment]
> Hmm, does HNC need to do anything to make this better? E.g. if you're using K8s 1.21+, you can simply modify the webhook manifests yourself to exclude the namespaces you want HNC to ignore.

As a user, I would expect the `excluded-namespace` flag supplied to HNC to fix this, but that might be a bit complicated to implement? 🤔

**Comment by adrianludwin** [comment]
They're not quite the same thing, since HNC enforces its own rules *on* the
namespaces (e.g. it prevents them from being arranged into hierarchies), it
just doesn't enforce policies *in* the namespace (i.e. the object
validator). Plus, even if it didn't work that way, there could be a period
of time during which the exclusion labels haven't yet been added to the
namespace, but the validator isn't awake yet.

IMO modifying the webhook config is far more understandable and
exponentially less work :)
