### ISSUE TITLE
Support customize namespace install

### ISSUE THREAD

**Issue by weilaaa** [kubernetes-sigs/hierarchical-namespaces#231]
It seems we can't install hnc in our customize namespace. Wish there was this feature.

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e9d8bb80e54ecfe735235ce608905e6dfbf757ca/internal/setup/webhooks.go#L26-L55

**Comment by adrianludwin** [comment]
This is nontrivial because you'd have to find all the places where
"hnc-system" is hardcoded, both in the configs and in the code, and replace
the former with kustomization and the latter with command-line args. I
suppose you could get away with just the command-line args if you didn't
mind modifying all the configs yourself.

I'm not going to make a PR for this myself but I'd be happy to accept one
if you wanted to submit it!

**Comment by xgp01** [comment]
Can I have a try?

**Comment by adrianludwin** [comment]
Thanks for the PR and sorry for all the delays, hopefully we can get this in soon :)
