### ISSUE TITLE
Support for "hns get pods -n my-hierarchical-ns"?

### ISSUE THREAD

**Issue by absoludity** [kubernetes-sigs/hierarchical-namespaces#235]
Hi there. I was excited to find hns today as a potential solution for some multi-tenancy queries users have which cannot be easily solved with vanilla k8s. There are two related requests that pop up in different scenarios for our application ([Kubeapps](https://kubeapps.dev/)):
- Can I see just the namespaces to which I have access? We currently solve this with a special service account that can list namespaces and then check to which namespaces a user has access (not great and expensive).
- Can I see all resource-x's in the namespaces to which I have access... effectively `kubectl hns get pods -n my-hierarchical-ns`

I can see ways that I could use hns to potentially answer the first point above, though I also note that the result [may be slow for the same reason](#223). It seems that currently this is answered client-side (by querying for the anchors in a namespace, then for those namespaces, recursively?).

So my questions are:
1. Are there plans, or has there been other requests, to move the hierarchical query server-side so that a single query can return the available namespaces in the tree? (I think you answered this with a "no" only 22 days ago on #223 :) ), and
2. If (1) was a possibility, could that be easily generalised to answer queries for resources within a hierarchy (eg. `kubectl hns get pods -n myhierarchical-ns`) on the server-side, rather than recursively visiting all namespaces and calling `get pods` etc. (assuming a user without read permission on the entire cluster).

I'm not certain, but it looks like doing so could not only solve the slow responses for `hns tree` but also allow users in a multi-tenant environment to see all their resources (similar to `kubectl get pods -A` but for a hierarchy rather than the whole cluster), which I imagine would be very useful to others as well?

Thanks for any thoughts (and for the great work on hns - I was very excited to find it... been a missing piece in k8s for a long time that Rancher and openshift have tried to fill in the past, imo).

**Comment by adrianludwin** [comment]
Hey @absoludity ! I'd love to be able to limit visibility to the namespaces you have access to, but base K8s doesn't support that and it'd be challenging for HNC to work around that. If we ever had to, I was planning on using something roughly similar to what you're describing, I think OpenShift has a similar approach too. Sadly, since HNC is just a layer on top of vanilla K8s, there's only so much we can do to modify the behaviour of built-in verbs like LIST.

So we definitely _could_ build something like this to move everything server-side, probably as an API extension rather than a controller. I'm not going to work on that myself, but I could help you with design, scoping, and reviews if you wanted to work on it. Sorry this isn't the best answer, I'm totally not _objecting_ to this feature, it just takes more time than I have right now!

**Comment by absoludity** [comment]
Thanks @adrianludwin, yes, I was just more wondering if it was something planned for the future. Unfortunately it's not something I'd be able to take time to do right now either. Cheers.

**Comment by adrianludwin** [comment]
Understood, thanks!

**Comment by cmurphy** [comment]
We discussed this at the February 21 meeting, I drafted a proposal to address this here https://docs.google.com/document/d/1WpnAJ3442v93G4Wi7SnoEiLZVLJJO-AWCkl5GO4YLl4/edit?usp=sharing

**Comment by cmurphy** [comment]
/remove-lifecycle stale

This is under development https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/281
