### ISSUE TITLE
Adding custom annotations to propagated objects

### ISSUE THREAD

**Issue by VainoTonis** [kubernetes-sigs/hierarchical-namespaces#245]
TLDR: Unsure if its possible to add a custom annotation to **only** propagated object and not the parent object

As the title suggest I am trying to figure out how and if it is possible to add a custom annotation to a propagated objects. From what I could understand there Is not a way to new annotation to a propagated object. Maybe I am completely wrong trying to do this, if so let me know!

**Comment by adrianludwin** [comment]
Hey @VainoTonis sorry for the delay in getting back to you.

Currently no, propagated objects are always copies of the parents. We've discussed proposals before that would allow you to make them different (or even omit the parent object completely - e.g. embed it in some other object) but none of them have ever been compelling enough for anyone to build.

If you can describe the usecase and you're interested in building it yourself, I'd be interested to discuss it. Thanks!

**Comment by VainoTonis** [comment]
Hello,  no worries thank you for the response! I should have asked this in Slack anyway.

I am testing a gitops environment where ArgoCD creates the parent namespace.For example I will use a Service Account as an object that is being propagated.  Then when we add child namespaces HNC  which adds the Service Account to child namespace. So far every component has worked as "advertised". We do not want nor need to do do a new Service Account for each and every child namespace so  ... propagation . 

But this creates a mismatch in ArgoCD since these Service Accounts are not in a manifest and thus the cluster state is out of sync. (ArgoCD does not have permissions to delete so its simply a visual thing) We can fix this by adding an annotation that tells ArgoCD to ignore that object. Currently in order to have that annotation added we need to add it to the parent namespace aswell. This creates a situation where when we delete the Service Account in the manifest the actual object stays as Argo is ignoring said object.

I would be interested in trying to add the feature myself but I have no experience with GO and somewhat limited programming knowledge (Limited to doing smaller things never in a large project like this).  Additionally I was not sure if this is a feature the project wants/needs.

**Comment by adrianludwin** [comment]
/remove-lifecycle stale

@VainoTonis I'm really sorry for my tardiness in getting back to you. Just been dealing with some maintainer burnout, but I'm getting back on top of things now.

Are you sure that you want to propagate service accounts? You can propagate the API objects, but that will just create many different SAs with similar names in different namespaces. For example, any permissions on the parent SA will _not_ propagate to the child SA. Is that what you want?

With that said, I understand your overall use case, and I agree that it might make sense to support it since I didn't realize ArgoCD would interact in this way with HNC.  It's reminding me a bit of #276 (cc @duduedri96) although I don't know if we can actually solve both the same way.

Anyway - I'd be open to having an annotation like `hnc.x-k8s.io/add-propagated-annotations` where the value is a delimited list of KVPs, maybe using semicolons or something, e.g. the value would look something like `argocd.io/ignore: true; other-example.com/foobar`. For the initial implementation that's probably good enough, but because it would mean we can't allow colons or semicolons in the propagated values, I'd also ensure we ban backslashes (i.e. `\`) so we can use that to escape characters in the future if we need to.

The right place to add this logic would be in the [`cleanSource` function](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/168dd7ebae3a6fd47bdbb649b44d5f96aa1a05c5/internal/objects/reconciler.go#L486), which looks at the source object and transforms it into the version that's going to be written to descendant namespaces. Banning backslashes would be done by adding a new validation function [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/168dd7ebae3a6fd47bdbb649b44d5f96aa1a05c5/internal/objects/validator.go#L144).

lmk if you're able to make and test this change, and I can help you with problems you run into (apart from basic Go issues).  But unfortunately I won't have time to make this change myself.

**Comment by duduedri96** [comment]
@VainoTonis I had the same experience with ArgoCD. The reason it happened is due to the fact that ArgoCD tracks its resources with an annotation that it adds to them when it deploys them. Then, if it couldn't find it in git, it decides that it needs to be removed. What you actually want is to cause HNC to NOT propagate this label, and then ArgoCD will just ignore this extra resource since there won't be anything that indicates that it is being tracked by Argo. The thing is, you can actually do this in HNC, however with annotations instead of labels. See the `--unpropagated-annotation` CLI argument in the [user guide](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/how-to.md#modify-command-line-arguments). You'd also need to change ArgoCD to use an annotation for tracking its resources instead of a label, see [here](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/#choosing-a-tracking-method). Combining these two should do what you need: cause ArgoCD to use an annotation for its tracking on resources, and prevent this annotation from being propagated.
