### ISSUE TITLE
Is Hierarchical Resource Quotas production-ready?

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/hierarchical-namespaces#247]
This repository has the CRD named `HierarchicalResourceQuota`. It's quite useful feature for cluster admins given we cannot limit the resource limit/request across multiple namespaces with a built-in `ResourceQuota`.
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/9102c4ddc2bbc145e279624d76d89f314a5485a6/api/v1alpha2/hierarchicalresourcequota_types.go#L25

It's introduced in https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/183 one year ago. But, the PR mentioned `certainly wouldn't recommend that anyone use it just yet`. Also, currently, there are no docs related to this feature.
Has the situation changed so far? Can we regard it as a production ready feature?

/kind documentation
/kind support
/wg multitenancy

**Comment by mochizuki875** [comment]
I don't know it has already been production ready.
However, it's seems to be disabled by default...

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/9102c4ddc2bbc145e279624d76d89f314a5485a6/cmd/manager/main.go#L154

https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/9102c4ddc2bbc145e279624d76d89f314a5485a6/internal/setup/reconcilers.go#L75-L106

**Comment by adrianludwin** [comment]
The main block here is https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/240. Once we merge that, we should be able to release v1.1 which will include HRQs. This will be the first release so I wouldn't call it prod-ready, but if you'd like to test it in your dev env for a month or two, we can patch up any problems we find and then call it prod ready.

It's based on code that was used in prod by other users some time ago (as part of a Google-specific product) but we've made a lot of changes since then to open-source it. I'm confident that the fundamental idea works, but there might be gotchas or edge cases here and there.

**Comment by sanposhiho** [comment]
@adrianludwin 

Please feel free to assign me on #240 if you want someone else to review it. I'd be happy to help to enhance this feature.

**Comment by sanposhiho** [comment]
I saw https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/240 got merged.
Given the original question is already clear, will close this issue. 

/close
