### ISSUE TITLE
usage of kind: SubnamespaceAnchor in Gitops

### ISSUE THREAD

**Issue by thiagolinhares** [kubernetes-sigs/hierarchical-namespaces#256]
Hi there.
We are experimenting with HNC and intend to use it as basis of our core deployments.
Our goal is to have a parent namespace, a service-account with "admin" privileges in that namespace, and configure its token to the GitOps flow, which will then manage all subnamespaces, roles, rolebinding and service-accounts for every subnamespace contained into this parent.
Reading your documentation we came across this section: [GitOps Integration](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/best-practices.md#gitops-integration)

> _Since HNC is controlled by regular Kubernetes objects, you can check your YAML files into source control and apply them to your cluster(s) via kubectl apply -f. You generally will only want to do this for your cluster-wide configuration (the HNCConfiguration object) and your full namespace configurations (the HierarchyConfiguration objects in each namespace),_` and not your subnamespaces (the SubnamespaceAnchor objects) since subnamespaces are mainly for unprivileged users, not Gitops flows.`

I wonder whether our approach is the right one, or should we rethink our CD?

**Comment by adrianludwin** [comment]
Hey @thiagolinhares , sorry for the delay in getting back to you.

Subnamespaces - that is, the things controlled by `SubnamespaceAnchor` - are really for humans to use, not for CI/CD. But you can have a _child_ namespace without it being a subnamespace. This is called a full namespace, and it's described [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#basic-subns). Basically, your CD would create the namespace, and then would create the `HierarchyConfiguration` object in that namespace pointing to its parent. From that point on, it would behave just like a subnamespace (all an anchor does is create the child namespace and that object for you).

While you _can_ use subnamespaces in CD, that's mainly a convenience feature for humans. I'd recommend just using full namespaces and setting up the hierarchical relationship yourself in your CD, because:

* There are fewer "moving parts" if something goes wrong
* The child namespace will exist more obviously in your repo than if there's this weird HNC-only "anchor" object that other people might not understand

But ultimately it's up to you. I hope this helps!

**Comment by adrianludwin** [comment]
Hi @thiagolinhares did this help? Please re-open the bug if you have more questions!

/close

**Comment by thiagolinhares** [comment]
> Hi @thiagolinhares did this help? Please re-open the bug if you have more questions!
> 
> /close

Yeah it did clarify many things!
We are evaluating our approach to a better fit.
For now, we won't use HNC at Gitops CD
