### ISSUE TITLE
Unable to update propagated CRD object

### ISSUE THREAD

**Issue by just1900** [kubernetes-sigs/hierarchical-namespaces#53]
I'm trying to use HNC to propagate CRD, but I find it does not sync the change I made to the source resource. And below is the event output via `kubectl hns describe monitor-res`, the message seems like hnc are updating resource without specifying `metadata.resourceVersion` ?
```
Last Seen Reason             Object                                  Message
9s        CannotUpdateObject AlertmanagerConfig:monitor-res/frontend Could not write from source namespace "monitor": alertmanagerconfigs.monitoring.coreos.com "frontend" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update.

```
any help would be appreciated.

**Comment by adrianludwin** [comment]
We are indeed [clearing out most of the metadata](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e20f5a832e3a6ce8b92bf3a6efed295abfebe589/internal/object/object.go#L27). It looks like for many core types, this works fine, but for CRDs, this may fail for updates (see e.g. https://github.com/kubernetes/kubernetes/issues/70674).

I think that in [writeObject](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/e20f5a832e3a6ce8b92bf3a6efed295abfebe589/internal/reconcilers/object.go#L569), before we overwrite `inst`, we should save its `resourceVersion` if it exists, and then reapply it after overwriting, e.g.:

```
+       // Copy useful information from the dest object (if it exists) before overwriting it)
	exist := inst.GetCreationTimestamp() != v1.Time{}
	ns := inst.GetNamespace()
+       rv := inst.Metadata.ResourceVersion // required for smooth updates
+
        // Overwrite the dest object from the source and reapply any critical information
	inst = object.Canonical(srcInst)
	inst.SetNamespace(ns)
+       inst.Metadata.ResourceVersion = rv
```

I'm not sure if that's the right syntax but you get the idea.

I don't have time to try this out now - @just1900, @RealHarshThakur, @rjbez17 , do any of you have the time to try this out?

**Comment by adrianludwin** [comment]
This seems like an important enough flaw that we should fix it in the next release.

**Comment by RealHarshThakur** [comment]
Might be able to try it on the weekend. Is there a release cadence being followed?

**Comment by adrianludwin** [comment]
No release cadence, we've generally released once we think we have enough
new features (less and less relevant these days as we reduce the rate of
new feature development) or bug fixes. Last summer it was pretty fast,
these days it's generally every few months.

**Comment by just1900** [comment]
@adrianludwin Thanks for point out the differnce between crd and core resource, it behaves normally when propagating cores resources like secret which confuse me a lot.
Actually, I've tried with resourceVersion, but it turns out if I update the instance with resourceVersion, webhook will reject the update request.

**Comment by adrianludwin** [comment]
@just1900 Yeah I didn't realize CRDs and core resources behaved differently (obviously - otherwise we would have tested both!). Also, apparently it's not exactly "CRD vs core resource" - it's "old resource types" (e.g. Deployments) vs "new resource types," one of which is custom resources. So there will be builtin types that have the save `resourceVersion` behaviour as CRs. Apparently. I haven't verified this myself :)

Yes, the HNC webhooks prevent any modification from what it thinks the propagated resource should be. This is almost always the right behaviour - unless HNC has a bug, like this one.

**Comment by just1900** [comment]
@adrianludwin aha, I guess I have misconfigured the SA when debugging locally, so the update request was rejected.
```
	ns := inst.GetNamespace()
	rv := inst.GetResourceVersion()
	inst = object.Canonical(srcInst)
	inst.SetNamespace(ns)
	inst.SetResourceVersion(rv)
```
I retried the piece of code above to update with resourceversion, and it worked.

**Comment by adrianludwin** [comment]
A PR would be great, thanks! Just a few quick pointers / requests:

* A change like this benefits from a _lot_ of comments, e.g. linking to this issue. Otherwise we'll have no idea why we added this in a few months.
* It would be great if you could add or update a unit test to verify that the rV is being copied (e.g. [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/42769da7fce8bd4c71a4ef2fd0735f43ce4710a7/internal/reconcilers/object_test.go#L367).
* It would be _amazing_ if you could update an end-to-end test (e.g. [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/test/e2e/issues_test.go)) to try to propagate a CRD, show that this fails without your fix, and that it passes with your fix.  [This](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/42769da7fce8bd4c71a4ef2fd0735f43ce4710a7/test/e2e/issues_test.go#L233) test is probably a pretty good model, and you can embed yaml in the test as shown [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/42769da7fce8bd4c71a4ef2fd0735f43ce4710a7/test/e2e/quickstart_test.go#L171).
  * The e2e tests assume that you've deployed HNC to a cluster, and your kubectl config is currently pointing at the cluster you want to run the tests on.
  * Running _all_ the e2e tests takes ~30min but you only need to run the one you're writing. So you can modify your test so that the `It()` function has an `F` (for "focus") in front of it, like this: `FIt()` (note the first two letters are capitalized). This will only run _your_ test. Just remember to change it back to `It()` before you submit the PR.
* We use one commit per PR so please squash all commits and force-update the PR branch if necessary. We also describe how we tested the change in the commit message like [this](https://github.com/kubernetes-sigs/hierarchical-namespaces/commit/0fa702a121605c7cfb3f935f95da412cbd27fb1d).
  * No worries if you forget any of this, I'll just remind you during the review process :) 

Thanks!
