### ISSUE TITLE
Add ability to exclude object from propagation based on a common label (fix configmap propagation with Istio)

### ISSUE THREAD

**Issue by and-1** [kubernetes-sigs/hierarchical-namespaces#66]
I work with hnc and use configmap propagation to child namespace. When i use hnc in cluster with installed istio, i experience with issue:
`{"level":"info","ts":1627985932.269383,"logger":"validators.Hierarchy","msg":"Denied","ns":"test","op":"CREATE","user":"system:serviceaccount:operators:shell-operator","code":409,"reason":"Conflict","message":"Cannot update hierarchy because it would overwrite the following object(s):\n  * Namespace \"test\": istio-ca-root-cert (/v1, Kind=ConfigMap)\nTo fix this, please rename or remove the conflicting objects first."}`
istio-ca-root-cert is configmap which istio create in all namespaces in cluster. I think hnc has to have extended exclude features based on label of resource or name.

**Comment by adrianludwin** [comment]
That's interesting, I didn't know about this use case. Thanks for submitting it.

You suggested excluding objects based on labels. Does Istio apply a common label to all objects that it creates? If so, I agree that this would be the best option. If not, we could go with names. Do you have the ability to create a PR?

I think this would be a safe addition to make because to exclude an object from propagation, you'd either need to be able to edit the object (in which case, you could just edit the existing exception annotations) or the HNCConfiguration, which is highly privileged. Therefore, this change doesn't open any new security holes. At most, it could _accidentally_ prevent something from being propagated if it _accidentally_ matched the exclusion criteria, but as long as the criteria are written to be tightly scoped, this hopefully won't be a problem.

**Comment by joe2far** [comment]
the `istio-ca-root-cert` does have a specific isitio.io/config label which could be used to exclude it
```
kubectl get cm istio-ca-root-cert -o yaml
...
  labels:
    istio.io/config: "true"
```
however the same issue holds, for the kubernetes created kube-root-ca.crt which does not have a label to easily exclude it on
```
kubectl get cm kube-root-ca.crt -o yaml
...
   which has no labels
```
given above I would prefer to have solution to exclude based upon specific resource names, this would solve both of the above examples and would follow a similar pattern to RBAC rules which allows api_group, api_version, resource/kind or resourceNames to be specified.

**Comment by adrianludwin** [comment]
Hey @joe2far sorry I didn't respond earlier but I've been on vacation since Labour Day.

Two quick questions. It looks like `kube-root-ca.crt` is now a built-in part of K8s, so I actually wouldn't mind hardcoding that into HNC, just like we've hardcoded in an exception for service account secrets. Otherwise every HNC user will need to set this up manually.

I'd _also_ be willing to hardcode the Istio exception since Istio is such a common usecase. This would let us delay any proposed changes to the API to see what other patterns come up. I would prefer to continue to use labels rather than names for exclusions, so it's unfortunate that the K8s root CA doesn't have a label but I can live with that.

wdyt about fully hardcoding the builtin K8s and Istio names for now? Also cc @rjbez17 - Ryan, do you agree with hardcoding all this for now?

**Comment by joe2far** [comment]
I have updated the PR - https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/81 to just contain the hardcodings for now
