### ISSUE TITLE
HNC Controller is reporting "Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io "config": the object has been modified"

### ISSUE THREAD

**Issue by rayterrill** [kubernetes-sigs/hierarchical-namespaces#75]
HNC Controller throws periodic errors:
```
Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io "config": the object has been modified; please apply your changes to the latest version and try again
```

```
{"level":"error","ts":1630010586.251877,"logger":"reconcilers.HNCConfiguration","msg":"Couldn't write singleton","error":"Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io \"config\": the object has been modified; please apply your changes to the latest version and try again"}
```

**Comment by rayterrill** [comment]
@adrianludwin It looks like we actually need to not propagate a label, not an annotation. Will the --unpropagated-annotations allow for removing labels? Or is there another way to do that?

**Comment by rayterrill** [comment]
I did build up a dev environment with Argo + HNC v0.8.0 and I see the same errors:
```
{"level":"error","ts":1630356464.003789,"logger":"reconcilers.HNCConfiguration","msg":"Could not update HNCConfiguration object","error":"Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io \"config\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":1630356464.0041895,"logger":"reconcilers.HNCConfiguration","msg":"Couldn't write singleton","error":"Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io \"config\": the object has been modified; please apply your changes to the latest version and try again"}
{"level":"error","ts":1630356464.0043757,"logger":"controller-runtime.manager.controller.hncconfiguration","msg":"Reconciler error","reconciler group":"hnc.x-k8s.io","reconciler kind":"HNCConfiguration","name":"config","namespace":"","error":"Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io \"config\": the object has been modified; please apply your changes to the latest version and try again"}
```

**Comment by minchao** [comment]
The problem is because Argo CD adds the `app.kubernetes.io/instance` label and uses it to determine which resources form the app.

A workaround is to add ignore annotation to resources so that these resource objects and propagated copies will be excluded from Argo CD sync (This only affects the sync status).

```yaml
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
```

References:

- [Why Is My App Out Of Sync Even After Syncing?](https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing)
- [Ignoring Resources That Are Extraneous](https://argo-cd.readthedocs.io/en/stable/user-guide/compare-options/)

**Comment by rayterrill** [comment]
Yep - this is exactly what we did to stop that issue, @minchao. :)

**Comment by adrianludwin** [comment]
@rayterrill sorry, are you saying that with the `IgnoreExtraneous` option, you're not seeing the errors in the logs anymore? Or just that it solved some other problem?

`--unpropagated-annotations` _only_ works for annotations, but it would be fairly trivial to extend it to cover labels as well (i.e. add an `--unpropagated-labels` flag). That would allow you to not have to change the Argo config. Would you be willing to make such a change?

**Comment by adrianludwin** [comment]
I'm also a bit confused as to what the problem was. The log errors were referring to problems with `HNCConfiguration`, but you mentioned problems with role bindings, not the HNC config. Was Argo _also_ trying to continuously re-sync `HNCConfiguration`?

**Comment by rayterrill** [comment]
Sorry all - I blurred multiple problems here.

This initial request was created because of the HNCConfiguration issue - "Operation cannot be fulfilled on hncconfigurations.hnc.x-k8s.io "config": the object has been modified; please apply your changes to the latest version and try again". After upgrading to v0.8.0, we are indeed still seeing this periodically.

We're wondering if this is just something we can ignore - if things get retried, maybe this is innocuous?

**Comment by adrianludwin** [comment]
It _can_ be ignored - that's the great thing about these controllers, they're pretty robust to failures. With that said, I'd kind of like to understand why it's happening in the first place. Learning that Argo was occasionally writing the HNCConfiguration object would certainly be an explanation. But it's not serious and can be ignored as long as it only happens from time to time.

lmk if you'd like to add an `--unpropagated-labels` option, I'd certainly be in favour of adding it.

**Comment by rayterrill** [comment]
@adrianludwin Unpropagated labels would be great. That would likely help with our argo case as well.

Is there anything we can do to get more detail on and troubleshoot why the HNCConfiguration issue is happening? Any debug logging or anything like that? I'm happy to help dig into it - just not totally sure where to start.

**Comment by adrianludwin** [comment]
Sorry, fell behind on my HNC work, lots of stuff going on these days plus I was off half of September...

The most important thing to know is if any _other_ system is writing the HNCConfiguration object. E.g. do you have Argo configured to write it? If so, these kinds of errors are expected and also harmless as long as they're relatively rare.

Failing that, if you're comfortable modifying HNC yourself, you could add log messages to whenever the HNCConfiguration controller is writing the object, including the [goroutine ID](https://gist.github.com/metafeather/3615b23097836bc36579100dac376906), just to confirm that HNC only writes it from one goroutine at a time (that _should_ be enforced by the `controller-runtime` library) and to see how often you're getting errors relative to the writes. Are you seeing this every time it writes? Does it look like it happens when HNC writes the same object twice in quick succession? It's a bit hard for me to give more advice since, in the absence of an external system getting in HNC's way, this error Should Never Happen (TM) 😁

**Comment by adrianludwin** [comment]
Hi @rayterrill please re-open this case if it's still a current issue, thanks!

/close
